[package]
name = "ponsic"
version = "0.1.0"
edition = "2024"

[target.'cfg(windows)'.dependencies]
ponsic-winsafe = { path = "../ponsic-winsafe" }

[dependencies]
inherits = "0.1.2"
lazy_static = "1.5.0"
