[package]
name = "ponsic-winsafe"
version = "0.1.0"
edition = "2024"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3.9", features = ["winuser", "wingdi", "libloaderapi","errhandlingapi"] }
